# https://neo4j.com/docs/operations-manual/current/fabric/configuration/#_cluster_setup_with_no_single_point_of_failure_example
version: '3'

networks:
  cluster_net:

services:

  prime1:
    hostname: prime1
    image: neo4j:5.6-enterprise
    networks:
      - cluster_net
    ports:
      - "17687:17687"
      - "17474:17474"
    volumes:
      - $HOME/tmp/docker/composite/neo4j-prime1/conf:/conf
      - $HOME/tmp/docker/composite/neo4j-prime1/data:/data
      - $HOME/tmp/docker/composite/neo4j-prime1/logs:/logs
      - $HOME/tmp/docker/composite/neo4j-prime1/metrics:/metrics
      - $HOME/tmp/docker/composite/neo4j-prime1/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode'='PRIMARY'
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_http_listen__address=:17474
      - NEO4J_server_http_advertised__address=localhost:17474
      - NEO4J_server_bolt_listen__address=:17687
      - NEO4J_server_bolt_advertised__address=localhost:17687
      - NEO4J_initial_dbms_default__database=db1

  prime2:
    hostname: prime2
    image: neo4j:5.6-enterprise
    networks:
      - cluster_net
    ports:
      - "27687:27687"
      - "27474:27474"
    volumes:
      - $HOME/tmp/docker/composite/neo4j-prime2/conf:/conf
      - $HOME/tmp/docker/composite/neo4j-prime2/data:/data
      - $HOME/tmp/docker/composite/neo4j-prime2/logs:/logs
      - $HOME/tmp/docker/composite/neo4j-prime2/metrics:/metrics
      - $HOME/tmp/docker/composite/neo4j-prime2/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode'='PRIMARY'
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_http_listen__address=:27474
      - NEO4J_server_http_advertised__address=localhost:27474
      - NEO4J_server_bolt_listen__address=:27687
      - NEO4J_server_bolt_advertised__address=localhost:27687
      - NEO4J_initial_dbms_default__database=db1

  prime3:
    hostname: prime3
    image: neo4j:5.6-enterprise
    networks:
      - cluster_net
    ports:
      - "37687:37687"
      - "37474:37474"
    volumes:
      - $HOME/tmp/docker/composite/neo4j-prime3/conf:/conf
      - $HOME/tmp/docker/composite/neo4j-prime3/data:/data
      - $HOME/tmp/docker/composite/neo4j-prime3/logs:/logs
      - $HOME/tmp/docker/composite/neo4j-prime3/metrics:/metrics
      - $HOME/tmp/docker/composite/neo4j-prime3/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode'='PRIMARY'
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_http_listen__address=:37474
      - NEO4J_server_http_advertised__address=localhost:37474
      - NEO4J_server_bolt_listen__address=:37687
      - NEO4J_server_bolt_advertised__address=localhost:37687
      - NEO4J_initial_dbms_default__database=db1

  composite:
    hostname: composite
    build:
      context: .
      dockerfile: composite.Dockerfile
      args:
        KEYSTORE_PWD: secret
    networks:
      - cluster_net
    links:
      - prime1
      - prime2
      - prime3
    ports:
      - "47474:47474"
      - "47687:47687"
    volumes:
      - $HOME/tmp/docker/composite/neo4j-composite/conf:/conf
      - $HOME/tmp/docker/composite/neo4j-composite/data:/data
      - $HOME/tmp/docker/composite/neo4j-composite/logs:/logs
      - $HOME/tmp/docker/composite/neo4j-composite/metrics:/metrics
      - $HOME/tmp/docker/composite/neo4j-composite/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode'='PRIMARY'
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_http_listen__address=:47474
      - NEO4J_server_http_advertised__address=localhost:47474
      - NEO4J_server_bolt_listen__address=:47687
      - NEO4J_server_bolt_advertised__address=localhost:47687
      - NEO4J_dbms_security_keystore_path=/composite.keystore
      - NEO4J_dbms_security_keystore_password=secret
      - KEYSTORE_PWD=secret
      - NEO4J_dbms_security_key_name=composite
