# sets a basic KAFKA infrastructure with broker, schema registry and connector and control center
# based on https://github.com/neo4j-contrib/neo4j-streams/blob/master/kafka-connect-neo4j/docker/docker-compose.yml
# control center can be reached via http://localhost:9021/
# 2 neo4j instances are configured: Neo4j3.5 and Neo4j 5
# URLS:
# * Neo4j 3.5
#   + browser: localhost:17474
#   + bolt: localhost:17687
# * Neo4j 5
#   + browser: localhost:27474
#   + bolt: localhost:27687

# load the streams plugin into Neo4j 3.5: (needed for cdc)
# mkdir -p $HOME/tmp/docker/kafka-neo4j-sync/neo4j35/plugins
# curl -L  https://github.com/neo4j-contrib/neo4j-streams/releases/download/3.5.13/neo4j-streams-3.5.13.jar --output $HOME/tmp/docker/kafka-neo4j-sync/neo4j35/plugins/neo4j-streams-3.5.13.jar --silent


# Once the services are loaded and running, activate the Connect plugin:
#
# sourceId strategy:
# curl -X POST http://localhost:8083/connectors \
#  -H 'Content-Type:application/json' \
#  -H 'Accept:application/json' \
#  -d @configs/neo4j-sync-sourceId.json

# schema strategy:
# curl -X POST http://localhost:8083/connectors \
#  -H 'Content-Type:application/json' \
#  -H 'Accept:application/json' \
#  -d @configs/neo4j-sync-schema.json

# mapped volumes are created under $HOME/tmp/docker/kafka-neo4j-sync/

networks:
  lan:

services:

  neo4j35:
    image: neo4j/neo4j-arm64-experimental:3.5.33-arm64
    networks:
      - lan
    hostname: neo4j35
    container_name: neo4j35
    ports:
      - "17474:17474"
      - "17687:17687"
    depends_on:
      - broker
      - connect
    volumes:
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j35/conf:/conf
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j35/data:/data
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j35/logs:/logs
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j35/metrics:/metrics
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j35/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:17474
      - NEO4J_dbms_connector_https_listen__address=:17473
      - NEO4J_dbms_connector_bolt_listen__address=:17687
      - NEO4J_kafka_zookeeper_connect=zookeeper:2181
      - NEO4J_kafka_bootstrap_servers=broker:9092
      - NEO4J_streams_sink_enabled=false
      - NEO4J_streams_source_enabled=true
      - NEO4J_streams_source.topic.nodes.neo4j=*
      - NEO4J_streams_source.topic.relationships.neo4j=*
      - NEO4J_streams_source_schema_polling_interval=10000
#      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=streams.*,apoc.*
      - NEO4J_dbms_allow__upgrade=true

  neo4j5:
    hostname: neo4j5
    image: neo4j:5.19.0-enterprise
    container_name: neo4j5
    networks:
      - lan
    ports:
      - "27687:27687"
      - "27474:27474"
    depends_on:
      - broker
      - connect
      - neo4j35
    volumes:
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j5/conf:/conf
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j5/data:/data
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j5/logs:/logs
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j5/metrics:/metrics
      - $HOME/tmp/docker/kafka-neo4j-sync/neo4j5/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_http_listen__address=:27474
      - NEO4J_server_https_listen__address=:27473
      - NEO4J_server_bolt_listen__address=:27687
      - NEO4J_initial_dbms_default__database=neo4j
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_logs_query_parameter__logging__enabled=true
      - NEO4J_db_logs_query_enabled=INFO

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - lan
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  broker:
    image: confluentinc/cp-server:7.6.1
    hostname: broker
    networks:
      - lan
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    volumes:
      - $HOME/tmp/docker/kafka-neo4j-sync/broker/data:/data
      - $HOME/tmp/docker/kafka-neo4j-sync/broker/logs:/logs
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092

      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  registry:
    image: confluentinc/cp-schema-registry:7.6.1
    networks:
      - lan
    hostname: registry
    container_name: registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_LOG4J_ROOT_LOGLEVEL: 'WARN'

  connect:
    image: cnfldemos/cp-server-connect-datagen:0.6.4-7.6.0
    networks:
      - lan
    hostname: connect
    container_name: connect
    depends_on:
      - broker
      - registry
    ports:
      - "8083:8083"
    volumes:
      - $HOME/tmp/docker/kafka-neo4j-sync/connect/plugins:/tmp/connect-plugins
    environment:
      CONNECT_LOG4J_ROOT_LOGLEVEL: 'WARN'
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://registry:8081
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.3.0.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/tmp/connect-plugins"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt neo4j/kafka-connect-neo4j:latest
        /etc/confluent/docker/run

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.1
    networks:
      - lan
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
      - registry
      - connect
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_ENABLE: false
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
      CONTROL_CENTER_LOG4J_ROOT_LOGLEVEL: 'WARN'
      CONTROL_CENTER_LOG4J_LOGGERS: 'kafka=WARN,kafka.controller=WARN,kafka.log.LogCleaner=WARN,state.change.logger=WARN,kafka.producer.async.DefaultEventHandler=WARN'
