version: '3'

networks:
  cluster_net:

services:

  srv1:
    hostname: srv1
    image: neo4j:5.26-enterprise
    networks:
      - cluster_net
    ports:
      - "7474:7474"
      - "6477:6477"
      - "7687:7687"
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-srv1/data:/data
      - $HOME/tmp/docker/cluster-simple/neo4j-srv1/logs:/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-srv1/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv1
      - NEO4J_server_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_server_tags=uneven
      - NEO4J_PLUGINS=["apoc"]

  srv2:
    hostname: srv2
    image: neo4j:5.26-enterprise
    networks:
      - cluster_net
    ports:
      - "27474:7474"
      - "26477:6477"
      - "27687:7687"
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-srv2/data:/data
      - $HOME/tmp/docker/cluster-simple/neo4j-srv2/logs:/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-srv2/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv2
      - NEO4J_server_bolt_advertised__address=localhost:27687
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_server_tags=even
      - NEO4J_PLUGINS=["apoc"]

  srv3:
    hostname: srv3
    image: neo4j:5.26-enterprise
    networks:
      - cluster_net
    ports:
      - "37474:7474"
      - "36477:6477"
      - "37687:7687"
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-srv3/data:/data
      - $HOME/tmp/docker/cluster-simple/neo4j-srv3/logs:/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-srv3/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv3
      - NEO4J_server_bolt_advertised__address=localhost:37687
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_server_tags=uneven
      - NEO4J_PLUGINS=["apoc"]

  srv4:
    hostname: srv4
    image: neo4j:5.26-enterprise
    networks:
      - cluster_net
    ports:
      - "47474:7474"
      - "46477:6477"
      - "47687:7687"
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-srv4/data:/data
      - $HOME/tmp/docker/cluster-simple/neo4j-srv4/logs:/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-srv4/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv4
      - NEO4J_server_bolt_advertised__address=localhost:47687
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_server_tags=even
      - NEO4J_PLUGINS=["apoc"]

  secondary1:
    hostname: secondary1
    image: neo4j:5.26-enterprise
    networks:
      - cluster_net
    ports:
      - "57474:7474"
      - "56477:6477"
      - "57687:7687"
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-secondary1/data:/data
      - $HOME/tmp/docker/cluster-simple/neo4j-secondary1/logs:/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-secondary1/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_initial_server_mode__constraint=SECONDARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=secondary1
      - NEO4J_server_bolt_advertised__address=localhost:57687
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_PLUGINS=["apoc"]
