version: '3'

networks:
  cluster_net:

services:

  srv1:
    hostname: srv1
    image: neo4j:5.1.0-enterprise
    networks:
      - cluster_net
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-srv1/conf:/var/lib/neo4j/conf
      - $HOME/tmp/docker/cluster-simple/neo4j-srv1/data:/var/lib/neo4j/data
      - $HOME/tmp/docker/cluster-simple/neo4j-srv1/logs:/var/lib/neo4j/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-srv1/metrics:/var/lib/neo4j/metrics
      - $HOME/tmp/docker/cluster-simple/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv1
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000
      - NEO4J_initial_dbms_default__primaries__count=3

  srv2:
    hostname: srv2
    image: neo4j:5.1.0-enterprise
    networks:
      - cluster_net
    ports:
      - 7475:7474
      - 6478:6477
      - 7688:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-srv2/conf:/var/lib/neo4j/conf
      - $HOME/tmp/docker/cluster-simple/neo4j-srv2/data:/var/lib/neo4j/data
      - $HOME/tmp/docker/cluster-simple/neo4j-srv2/logs:/var/lib/neo4j/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-srv2/metrics:/metrics
      - $HOME/tmp/docker/cluster-simple/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv2
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000
      - NEO4J_initial_dbms_default__primaries__count=3

  srv3:
    hostname: srv3
    image: neo4j:5.1.0-enterprise
    networks:
      - cluster_net
    ports:
      - 7476:7474
      - 6479:6477
      - 7689:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-srv3/conf:/var/lib/neo4j/conf
      - $HOME/tmp/docker/cluster-simple/neo4j-srv3/data:/var/lib/neo4j/data
      - $HOME/tmp/docker/cluster-simple/neo4j-srv3/logs:/var/lib/neo4j/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-srv3/metrics:/var/lib/neo4j/metrics
      - $HOME/tmp/docker/cluster-simple/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv3
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000
      - NEO4J_initial_dbms_default__primaries__count=3


