# derivation of the simple-cluster, but with ssl enable.
# all neo4j instances rely on a 'ssl' service, which is an nginx image used to create self-signed certificates via openssl.
# the certs are made available to the neo4j services via volumes. All public certs go into the 'trusted_certs' volume that is mapped
# into all neo4j services under '/trusted_certs' and this directory is configured as 'trusted_dir' in all instances so that the instances trust each other
# private keys have each their own volume and are mapped/configured accordingly.

# the trusted volume has the following entries:
# docker run --rm -i -v=neo4j-compose_trusted_certs:/tmp/trusted busybox ls -l /tmp/trusted
# total 16
# -rw-r--r--    1 root     root          1261 Jun  1 16:46 core1.pem
# -rw-r--r--    1 root     root          1261 Jun  1 16:46 core2.pem
# -rw-r--r--    1 root     root          1261 Jun  1 16:46 core3.pem
# -rw-r--r--    1 root     root          1261 Jun  1 16:46 read1.pem

# ssl is enabled for https, bolt, backup and cluster scopes

version: '3'

networks:
  cluster_net:

volumes:
  trusted_certs:
  srv1_priv:
  srv2_priv:
  srv3_priv:
  srv4_priv:

services:

  ssl:
    image: nginx
    volumes:
      - trusted_certs:/trusted:rw
      - srv1_priv:/srv1:rw
      - srv2_priv:/srv2:rw
      - srv3_priv:/srv3:rw
      - srv4_priv:/srv4:rw
    command:
      - bash
      - -c
      - |
        openssl req -out -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/C=de/L=BY/L=Munic/O=Neo4j/CN=core1" -keyout /srv1/private.key -out /srv1/public.crt
        chmod 666 /srv1/private.key
        chmod 666 /srv1/public.crt
        cp /srv1/public.crt /trusted/srv1_public.crt
        openssl req -out -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/C=de/L=BY/L=Munic/O=Neo4j/CN=core2" -keyout /srv2/private.key -out /srv2/public.crt
        chmod 666 /srv2/private.key
        chmod 666 /srv2/public.crt
        cp /srv2/public.crt /trusted/srv2_public.crt
        openssl req -out -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/C=de/L=BY/L=Munic/O=Neo4j/CN=core3" -keyout /srv3/private.key -out /srv3/public.crt
        chmod 666 /srv3/private.key
        chmod 666 /srv3/public.crt
        cp /srv3/public.crt /trusted/srv3_public.crt
        openssl req -out -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/C=de/L=BY/L=Munic/O=Neo4j/CN=read1" -keyout /srv4/private.key -out /srv4/public.crt
        chmod 666 /srv4/private.key
        chmod 666 /srv4/public.crt
        cp /srv4/public.crt /trusted/srv4_public.crt

  srv1:
    hostname: srv1
    image: neo4j:5.1.0-enterprise
    depends_on:
      - ssl
    networks:
      - cluster_net
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv1/conf:/conf
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv1/data:/data
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv1/logs:/logs
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv1/metrics:/metrics
      - trusted_certs:/trusted_certs
      - srv1_priv:/priv
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv1
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_dbms_default__primaries__count=3
      - NEO4J_dbms_ssl_policy_cluster_enabled=true
      - NEO4J_dbms_ssl_policy_cluster_base__directory=/priv
      - NEO4J_dbms_ssl_policy_cluster_private__key=private.key
      - NEO4J_dbms_ssl_policy_cluster_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_cluster_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_backup_enabled=true
      - NEO4J_dbms_ssl_policy_backup_base__directory=/priv
      - NEO4J_dbms_ssl_policy_backup_private__key=private.key
      - NEO4J_dbms_ssl_policy_backup_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_backup_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/priv
      - NEO4J_dbms_ssl_policy_bolt_private__key=private.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_bolt_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/priv
      - NEO4J_dbms_ssl_policy_https_private__key=private.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_https_trusted__dir=/trusted_certs

  srv2:
    hostname: srv2
    image: neo4j:5.1.0-enterprise
    depends_on:
      - ssl
    networks:
      - cluster_net
    ports:
      - 7475:7474
      - 6478:6477
      - 7688:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv2/conf:/conf
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv2/data:/data
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv2/logs:/logs
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv2/metrics:/metrics
      - trusted_certs:/trusted_certs
      - srv2_priv:/priv
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv2
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_dbms_default__primaries__count=3
      - NEO4J_dbms_ssl_policy_cluster_enabled=true
      - NEO4J_dbms_ssl_policy_cluster_base__directory=/priv
      - NEO4J_dbms_ssl_policy_cluster_private__key=private.key
      - NEO4J_dbms_ssl_policy_cluster_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_cluster_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_backup_enabled=true
      - NEO4J_dbms_ssl_policy_backup_base__directory=/priv
      - NEO4J_dbms_ssl_policy_backup_private__key=private.key
      - NEO4J_dbms_ssl_policy_backup_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_backup_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/priv
      - NEO4J_dbms_ssl_policy_bolt_private__key=private.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_bolt_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/priv
      - NEO4J_dbms_ssl_policy_https_private__key=private.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_https_trusted__dir=/trusted_certs

  srv3:
    hostname: srv3
    image: neo4j:5.1.0-enterprise
    depends_on:
      - ssl
    networks:
      - cluster_net
    ports:
      - 7476:7474
      - 6479:6477
      - 7689:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv3/conf:/conf
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv3/data:/data
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv3/logs:/logs
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv3/metrics:/metrics
      - trusted_certs:/trusted_certs
      - srv3_priv:/priv
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv3
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_dbms_default__primaries__count=3
      - NEO4J_dbms_ssl_policy_cluster_enabled=true
      - NEO4J_dbms_ssl_policy_cluster_base__directory=/priv
      - NEO4J_dbms_ssl_policy_cluster_private__key=private.key
      - NEO4J_dbms_ssl_policy_cluster_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_cluster_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_backup_enabled=true
      - NEO4J_dbms_ssl_policy_backup_base__directory=/priv
      - NEO4J_dbms_ssl_policy_backup_private__key=private.key
      - NEO4J_dbms_ssl_policy_backup_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_backup_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/priv
      - NEO4J_dbms_ssl_policy_bolt_private__key=private.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_bolt_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/priv
      - NEO4J_dbms_ssl_policy_https_private__key=private.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_https_trusted__dir=/trusted_certs

  srv4:
    hostname: srv4
    image: neo4j:5.1.0-enterprise
    depends_on:
      - ssl
    networks:
      - cluster_net
    ports:
      - 7477:7474
      - 6480:6477
      - 7690:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv4/conf:/conf
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv4/data:/data
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv4/logs:/logs
      - $HOME/tmp/docker/cluster-simple-ssl/neo4j-srv4/metrics:/metrics
      - trusted_certs:/trusted_certs
      - srv4_priv:/priv
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=srv4
      - NEO4J_dbms_cluster_discovery_endpoints=srv1:5000,srv2:5000,srv3:5000,srv4:5000
      - NEO4J_initial_dbms_default__primaries__count=3
      - NEO4J_dbms_ssl_policy_cluster_enabled=true
      - NEO4J_dbms_ssl_policy_cluster_base__directory=/priv
      - NEO4J_dbms_ssl_policy_cluster_private__key=private.key
      - NEO4J_dbms_ssl_policy_cluster_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_cluster_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_backup_enabled=true
      - NEO4J_dbms_ssl_policy_backup_base__directory=/priv
      - NEO4J_dbms_ssl_policy_backup_private__key=private.key
      - NEO4J_dbms_ssl_policy_backup_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_backup_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/priv
      - NEO4J_dbms_ssl_policy_bolt_private__key=private.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_bolt_trusted__dir=/trusted_certs
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/priv
      - NEO4J_dbms_ssl_policy_https_private__key=private.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_https_trusted__dir=/trusted_certs

